#!/bin/bash
# $2 - path, $1 - string in quotes
if [ "2" -eq "$#" ]     #number of params
then
    if [ -n "$1" ]      #null string
    then
        if [ -d "$2" ]      #incorrect path
        then    #searching
            res=$( ( find "$2" -type f  -exec grep -ql "^$1$" {}   \; -printf '%s %P\n') | sort -k1 )
            echo -e "$res"
        else
            echo -e "ERR: Incorrect path" >&2
        fi
    else
        echo -e "ERR: null string for searching" >&2
    fi
else
    echo -e "This script expect 2 parameters: \n    First - string in quotes \n    Second - directory for searching" >&2
fi

